apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: stack-istio
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/stack-istio
    meta.crossplane.io/description: Installs Istio (base, istiod, gateways) via Helm with a minimal, stable interface.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.1.0"
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: ">=v0.18.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
